const sampleNews = [
    {
        title: "Hina Khan diagnosed with stage 3 breast cancer: Why cases are rising among younger women",
        description: "Hina Khan bravely battles breast cancer, emphasizing lifestyle risks and genetic factors in her fight against the disease. As reported by the journal Cancer, breast cancer remains the most common cancer among women in India, accounting for 28.2% of all female cancers, with an alarming estimate of 216,108 cases by 2022.",
        publisDate: new Date(),
        image: "https://static.toiimg.com/thumb/msid-111335414,imgsize-41242,width-400,resizemode-4/111335414.jpg",
        tags: "#cancer #hinakhan #GetWellSoon",
        source:"Times of India",
    },
    {
        title: "Could Getting Enough Sleep Help Prevent Osteoporosis?",
        description: "In people's early- to mid-20s, they reach what is called peak bone mineral density, which is higher for men than it is for women, according to researchers. This peak is one of the main determinants of fracture risk later in life. After reaching this peak, a person's bone density remains roughly stable for a couple of decades. Then, when women enter the menopausal transition, they experience accelerated bone loss. Men also experience bone density decline as they age. Sleep patterns also evolve over time.",
        publisDate: new Date(),
        image:"https://www.eurasiareview.com/wp-content/uploads/2022/04/a-136-800x445.png",
        tags:"#sleep #osteoporosis",
        source:"University of Colorado Anschutz Medical Campus",
    },
    {
        title: "Women are 40% more likely to experience depression during the perimenopause",
        description: "Women are 40% more likely to experience depression in the perimenopause than those who aren't experiencing any menopausal symptoms, finds a new study.",
        publisDate: new Date(),
        image:"https://www.ucl.ac.uk/news/sites/news/files/styles/large_image/public/menopause_depression-fotor-2024050194610.jpg?itok=dcrwZeP6",
        tags: "#depresssion #perimenopause",
        source:"University College London",
    },
    {
        title: "Removal of ovaries before menopause associated with reduced white matter in brain",
        description: "Women who have their ovaries removed before menopause, particularly before the age of 40, have reduced white matter integrity in multiple regions of the brain later in life, a new study suggests. White matter refers to the nerve fibers that connect neurons in different areas of the brain.",
        publisDate: new Date(),
        image:"https://images.mid-day.com/images/images/2024/jun/menopause_d_d.webp",
        tags:"#ovaries #menopause #brain",
        source:"Atrium Health Wake Forest Baptist",
    },
    {
        title: "Kenya increases access to modern contraceptives to drive down maternal mortality",
        description: "Kenya is seeking to reduce maternal mortality by increasing access to modern contraceptives for women who have just given birth, or had an abortion or miscarriage, the country’s health ministry has said.",
        publisDate: new Date(),
        image:"https://d2jx2rerrg6sh3.cloudfront.net/images/health/16_310x240.jpg",
        tags:"#maternal morality",
        source:"https://www.scidev.net/global/news/kenya-rolls-out-contraceptives-to-reduce-maternal-deaths",
    },
    {
        title: "PCOS linked to higher risk of adverse birth outcomes",
        description: "Meta-analyses conducted on women with PCOS have revealed more adverse outcomes like perinatal mortality, admission to neonatal intensive care units (NICUs), lower mean birth weight, and higher preterm birth relative to women without PCOS. However, some gaps exist in research.",
        publisDate: new Date(),
        image:"https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20240705065949/ri/950/src/images/news/ImageForNews_784535_17201771831581200.jpg",
        tags:"#risk #birth outcomes",
        source:"https://www.news-medical.net/medical/authors/priyom-bose",
    },
    {
        title: "More than 1,000 small changes in DNA identified that influence age of first period",
        description: "In a recent study published in Nature Genetics, researchers examined nearly 800,000 women's deoxyribonucleic acid (DNA) to explore puberty timing complexities. They identified signals related to menarche timing and investigated their influence on puberty onset.",
        publisDate: new Date(),
        image:"https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20240704091034/ri/1000/src/images/news/ImageForNews_784499_17200986340173296.jpg",
        tags:"#DNA #periods",
        source:"https://www.news-medical.net/medical/authors/pooja-toshniwal-paharia-toshniwal-paharia",
    },
    {
        title: "Study reveals potential chemical risks in healthy diets for pregnant women",
        description: "A recent Nature Food journal study utilized data from a racially and ethnically diverse cohort in the United States to determine whether adherence to healthy dietary patterns increases the risk of exposure to potentially harmful environmental contaminants during pregnancy.",
        publisDate: new Date(),
        image:"https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20240703120303/ri/950/src/images/news/ImageForNews_784436_17200225818371006.jpg",
        tags:"#pregnancy #healthy diets",
        source:"https://www.news-medical.net/medical/authors/priyom-bose",
    },
    {
        title: "Exposure to second-hand smoke raises breast cancer risk in non-smokers by 24%, study reveals",
        description: "The meta-analysis of selected studies showed that female non-smokers are at a 24% increased risk of developing breast cancer when exposed to second-hand smoke. The risk of breast cancer was significantly higher in case-control studies than in cohort studies.",
        publisDate: new Date(),
        image:"https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20240701083733/ri/950/src/images/news/ImageForNews_784250_17198806452933611.jpg",
        tags:"#smoke #cancer",
        source:" https://www.nature.com/articles/s41416-024-02732-5 ",
    },
    {
        title: "States With Abortion Measures on the Ballot in 2024",
        description: "Voters will weigh in on the right to abortion in at least five states later this year. Since the Supreme Court two years ago overturned the national right to abortion and returned its regulation to state legislatures, activists have pushed to get abortion measures on ballots in states across the country.",
        publisDate: new Date(),
        image:"https://www.usnews.com/object/image/00000190-1226-d2bb-adfb-f6e69de10000/gettyimages-1241582098.jpg?update-time=1718293287609&size=responsive970",
        tags:"#abortion #latest news",
        source:"https://www.usnews.com/",
    },
    {
        title: "Pakistan's gender gap index hits rock bottom, second worst globally",
        description: "Lahore [Pakistan]: In the latest Global Gender Gap Index by the World Economic Forum (WEF), Pakistan finds itself near the bottom of the list, with only Sudan ranked lower among 146 nations surveyed. This marks a further decline from its 142nd position last year, reflecting a worsening situation for women in the country, Dawn reported.",
        publisDate: new Date(),
        image:"https://img.etimg.com/thumb/msid-111547304,width-300,height-225,imgsize-46722,resizemode-75/pakistans-gender-gap.jpg",
        tags:"#gender gap",
        source:"https://economictimes.indiatimes.com/topic/world-economic-forum",
    },
    {
        title: "Woman spends £15k freezing eggs for future baby",
        description: "An endometriosis patient spent her house deposit freezing her eggs so she can have children in future.Sophie Richards, from Carmarthen, spent the cash because her condition was not covered by NHS fertility support.In total- including expenses like travel, blood tests and scans - it cost her £15,000.The 27-year-old said she was keeping my fingers crossed treatment would be available on the NHS in future.Edited by Greg Davies",
        publisDate: new Date(),
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCuAegiAq_ITr2asYFD_4Avocgn41dgOQx4R6SIn5Izj2VW_O2xmEofehwrw&s",
        tags:"#future baby #eggs #women",
        source:"https://www.bbc.com/news/videos/c977ydxx4p1o",
    },
    {
        title: "Misleading ads risking women's health, doctors say",
        description: "Women are being targeted and exploited by a rise in poorly evidenced, alternative treatments online as NHS services struggle to keep up with demand, doctors and campaigners have said.",
        publisDate: new Date(),
        image:"https://ichef.bbci.co.uk/news/480/cpsprodpb/97cf/live/bb746100-0ec4-11ef-82e8-cd354766a224.jpg.webp",
        tags:"#ads #women's health",
        source:"https://www.bbc.com/news/articles/cl5kpe2z489o",
    },
    {
        title: "New menopause support group set up in York",
        description: "A new support group for women going through the menopause has been launched in York.The group was set up by York Women's Counselling Service (YWCS) after it surveyed more than 300 women in the city about what help they needed.Many of the respondents said there was a lack of support for the psychological symptoms of the menopause.",
        publisDate: new Date(),
        image:"https://ichef.bbci.co.uk/news/480/cpsprodpb/3f02/live/bdae9240-0e03-11ef-8782-d9472c11dd3d.jpg.webp",
        tags:"# menopause #york",
        source:"https://www.bbc.com/news/articles/cjljg5ezdewo",
    },
    {
        title: "Health initiative 'rolling stone that will gather pace'",
        description: "One hundred women have gathered to share their stories and experiences of resilience amid health problems. Some of them have cancer or autoimmune diseases, and some have experienced infertility or baby loss, but they have all come together as part of the Mortal and Strong project. Three of the 100 women explain what being involved in the project means to them.",
        publisDate: new Date(),
        image:"https://ichef.bbci.co.uk/news/480/cpsprodpb/58c6/live/1e142850-f8e9-11ee-8369-47dc4454b972.jpg.webp",
        tags:"#stone #health",
        source:"https://www.bbc.com/news/articles/c4n14jd30n9o",
    },
    {
        title: "Patients at risk as maternity staff 'burned out'",
        description: "Patients are at risk on maternity wards at Middlesbrough's James Cook University Hospital, a watchdog found.Staff shortages, security concerns, inadequate surroundings and delays to care are among failings highlighted in a Care Quality Commission (CQC) report.Overstretched idwives are struggling to give mothers and babies the care they need, the CQC suggests.",
        publisDate: new Date(),
        image:"https://ichef.bbci.co.uk/news/480/cpsprodpb/cbb9/live/e0096d70-b605-11ee-9688-cd697cd0ec7c.jpg.webp",
        tags:"#maternity #patients #health",
        source:"https://www.bbc.com/news/articles/czqvq9xnd1zo",
    },
    {
        title: "If you’re pregnant, how accurate is your ‘due date’?",
        description: "More than 1,700 pregnant women in South Australia have reportedly been given the wrong “due date” due to a technical error in their computerised medical records. This has prompted concerns some women may have had an early induction of labour as a result.",
        publisDate: new Date(),
        image:"https://media.istockphoto.com/id/1835179103/photo/pregnant-woman-holds-hands-on-her-belly-pregnancy-maternity-preparation-and-expectation.jpg?s=2048x2048&w=is&k=20&c=w6yuyQjQcanGpqybdpcGPDca6Z3UZZ86oMUkT8uuboE=",
        tags:"#pregnancy #women #health",
        source:"https://theconversation.com/if-youre-pregnant-how-accurate-is-your-due-date-233547",
    },
    {
        title: "NHS Kent and Medway launch women's health survey",
        description: "The NHS is calling for people in Kent and Medway to share their views on women's health.The survey is part of a national women's health strategy to put more support in place for health issues including periods, pregnancy and the menopause.“There are so many health issues unique to women and those born female and some experience quite poor health as a result, said Dr Kate Langford, chief medical officer and women's health champion at NHS Kent and Medway.",
        publisDate: new Date(),
        image:"https://ichef.bbci.co.uk/news/1024/cpsprodpb/e7c9/live/63285bc0-a59a-11ee-bc2f-cb5579b90709.jpg.webp",
        tags:"#women's health #survey",
        source:"https://www.bbc.com",
    },
    {
        title: "Your favorite drink can cause breast cancer – but most women in the US aren’t aware of alcohol’s health risks",
        description: "Did you know that casual drinks with friends or having a “wine mom” moment to unwind could actually be nudging up your risk for breast cancer? It sounds like a buzzkill. But it’s a truth that many might not know: Alcohol actually causes breast cancer.",
        publisDate: new Date(),
        image:"https://images.theconversation.com/files/596956/original/file-20240528-19-vhac78.jpg?ixlib=rb-4.1.0&rect=161%2C0%2C1412%2C1412&q=45&auto=format&w=240&h=240&fit=crop",
        tags:"alcohol #drink #breast cancer",
        source:"https://theconversation.com/global",
    },
    {
        title: "Menstrual Health Day 2024: How the period cycle affects your sleep and body",
        description: "Menstrual Health Day 2024: It is important to understand the relationship between menstrual health and sleep is essential for women to manage their cycles effectively and maintain good health.",
        publisDate: new Date(),
        image:"https://www.financialexpress.com/wp-content/uploads/2024/05/alarm-clock-surrounded-by-tampons.jpg?resize=400,225",
        tags:"#periods #menstrual health #body",
        source:"https://www.financialexpress.com/",
    },
    
]
module.exports = { data: sampleNews};
